### ISSUE TITLE
Connecting to GrapheneDB with perl driver

### ISSUE THREAD

**Issue by caribnow** [majensen/rest-neo4p#1]
Hi, I am going through your blog post tutorial and trying to connect to a sandbox instance of Neo4j on GrapheneDB. Unfortunately I keep getting an 'Unauthorized' error. I am using the basic connection string

REST::Neo4p->connect( $server, $user, $pass );

with my appropriate host URL, username, and password as specified in my GrapheneDB console's connection tab. What am I missing here?

Here is my exact connection snippet.

eval {
    REST::Neo4p->connect($url, $username, $password);
};
ref $@ ? $@->rethrow : die $@ if $@; 

Thanks in advance.

**Comment by majensen** [comment]
Sorry I missed this -- were you able to work it out? If not, I will look into it-

**Comment by caribnow** [comment]
Everything is good.

On Thu, Mar 19, 2015 at 1:39 PM, Mark Jensen notifications@github.com
wrote:

> Sorry I missed this -- were you able to work it out? If not, I will look
> into it-
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/majensen/rest-neo4p/issues/1#issuecomment-83690221.

## 

Kwesi K. Steele
http://www.kwesisteele.com/

**Comment by christianaranda** [comment]
Would you mind sharing what you did?  You could potentially help people who have the same issue, like me.  Thanks in advance.

**Comment by majensen** [comment]
Sorry about this, but if you're using the 2.2 server, the basic authentication in Neo4p isn't in the distro yet. Hope to have it up in a few days.

**Comment by christianaranda** [comment]
Thanks for the quick reply.  Really appreciate what you created.
