### ISSUE TITLE
How to delete relationship?

### ISSUE THREAD

**Issue by foobargeez** [majensen/rest-neo4p#16]
Hello,
I could be missing something obvious but is there a way to delete a relationship?

Thanks!

**Comment by majensen** [comment]
Hey @foobargeez - yes, you should be able to simply do

``$rel->remove;``

Let me know if this doesn't work

**Comment by foobargeez** [comment]
Thanks -- worked.  Created https://github.com/majensen/rest-neo4p/pull/17 to document the method.
