### ISSUE TITLE
Can't connect to neo4j(latest version)

### ISSUE THREAD

**Issue by nakatatsu-paon** [majensen/rest-neo4p#22]
REST::Neo4p does not support the latest version of Neo4j?
When I use the latest version of Neo4j, I get the following error.

`"URL missing (connect phase 2)"`

It seems to be directly caused by the fact that the URL is not set at the time of the second connection, although it is connected twice in the process of doing "&connect()”.
https://github.com/majensen/rest-neo4p/blob/3330db42915c16a2e88497b55f033801000c116c/lib/REST/Neo4p/Agent.pm#L80

"&connect()" is trying to get the URL from the response on the first connection, but since it doesn't return the "data" field, I guess the URL is not set on the second connection.

Thanks!

**Comment by nakatatsu-paon** [comment]
It was occurring using version 4.1.1.
It works with version 3.5.

Does REST::Neo4p plan to support "version 4.x"?

**Comment by majensen** [comment]
@nakatatsu-paon - thanks for the issue and for digging in to it. Neo4j 4.0 introduced a number of breaking changes that require some significant rewriting of code. I do want to make it work with 4.0, but have limited time at the moment to do the work. This is definitely on the roadmap - just need to carve out time.

**Comment by majensen** [comment]
@nakatatsu-paon  - In the meantime, please take a look at 
[Neo4j::Driver](https://metacpan.org/pod/Neo4j::Driver) by @johannessen  - This operates at a more direct level with Neo4j than REST::Neo4p. It communicates with Neo4j 4.0 and has many nice features (it will likely be the basis for upgrading REST::Neo4p).

**Comment by nakatatsu-paon** [comment]
I did a little research and it seems that the system has changed significantly between 4.x and 3.5.
It's hard for developers...

Thank you for the information.
I'll use Neo4j::Driver.

**Comment by majensen** [comment]
@nakatatsu-paon I just wanted to let you know that I've been working on a major update to rest-neo4p that incorporates neo4j-driver and should work with Neo4j 4. There is still work to do but I hope in a week or so to have a release. If you're interested, the development in the [feat-neo4j-driver](https://github.com/majensen/rest-neo4p/tree/feat-neo4j-driver) branch of the repo.

**Comment by johannessen** [comment]
Looking good! I took the liberty to leave a few comments in the commits. Please let me know if you need something from my end.

**Comment by majensen** [comment]
https://metacpan.org/pod/REST::Neo4p is released at v0.4000 - it should work with Neo4j version 4.0 now, @nakatatsu-paon (thanks to @johannessen and Neo4j::Driver). 

If you are still interested, please take a look. If you see any problems, just make a ticket here.
thanks!
