### ISSUE TITLE
Test framework with Neo 2.2 server

### ISSUE THREAD

**Issue by majensen** [majensen/rest-neo4p#3]
Do it.

**Comment by cheerfulstoic** [comment]
Curious about the status of this!  I'm not much of a Perl programmer, but I'm a Developer Advocate for Neo4j and wanted to help make sure that REST::Neo4p was ready for 2.2.  Also, let me know if you need any help with 2.2 or anything else Neo4j-wise!

**Comment by majensen** [comment]
Making some progress on basic authentication. After that is done I will 
run the regressions. Unfortunately there haven't been many tuits for 
this.
thanks

**Comment by cheerfulstoic** [comment]
Awesome, thanks ;)
