### ISSUE TITLE
Add support to REST::Neo4p to pass dbname to Neo4j::Driver agent

### ISSUE THREAD

**Issue by foobargeez** [majensen/rest-neo4p#32]
Hello,
Neo4j::Driver agent accepts server address and dbname for it's `connect()` method but REST::Neo4p doesn't have support to pass dbname to the agent.  This is needed to work with v4.x version where we can have multiple databases in a single instance.

Happy to submit a patch if you prefer or please do the needful.

Thanks!

**Comment by foobargeez** [comment]
A simple workaround to get my setup moving to neo4j v4.x is to specify the default DB in neo4j config to whatever I would like to connect/test against.  Bug the changes to make REST::Neo4p pass dbname to Neo4j::Driver agent doesn't seem to be involved either ..

**Comment by foobargeez** [comment]
> A simple workaround to get my setup moving to neo4j v4.x is to specify the default DB in neo4j config to whatever I would like to connect/test against

Oops, this didn't work.

Let me get a patch ready as this is blocking me.

**Comment by johannessen** [comment]
>> A simple workaround to get my setup moving to neo4j v4.x is to specify the default DB in neo4j config to whatever I would like to connect/test against
> 
> Oops, this didn't work.

My understanding is this *should* work. Does the Cypher command `SHOW DEFAULT DATABASE` actually produce the same database name you specified in neo4j.conf? If not, it means Neo4j didn’t read your config for some reason.

**Comment by foobargeez** [comment]
`SHOW DEFAULT DATABASE` shows the DB that I want to connect to, so all good there.

I modified the code to pass a database name but that didn't work either .. so the issue is somewhere/something else.  I am still digging.  Will post once I understand the issue better.

FWIW, I had to init `$Neo4j::Bolt::DEFAULT_DB` for Neo4j::Bolt too .. it didn't automatically connect to the default database.

**Comment by johannessen** [comment]
So, I got curious and looked into this. Turns out the line I had suggested previously in https://github.com/majensen/perlbolt/issues/48#issuecomment-1008486047 works just fine on my system.

I also discovered #33. If you’ve been trying to test database connectivity using REST::Neo4p::Query, this may have been the source of your trouble.

As for Bolt, you’re right: It sits at a lower level and unlike the driver (and by extension Neo4p), it doesn’t automatically determine the configured default database. You would need to get that manually using the Cypher command given above.

**Comment by foobargeez** [comment]
> I also discovered #33. If you’ve been trying to test database connectivity using REST::Neo4p::Query, this may have been the source of your trouble.

This is super helpful -- thanks for pointing it out.

I manually made the above change in my local installation and Neo4p v0.4001 is now able to talk and execute queries against Neo4j v4.x.  We really need to get the #33 patch out.  @majensen, can you please expedite the release?

I am all set -- thanks @johannessen for all your help!

**Comment by majensen** [comment]
pushed to PAUSE as v0.4003 just now gentlemen

**Comment by johannessen** [comment]
@majensen Thank you sir! Could you also push [majensen/perlbolt](https://github.com/majensen/perlbolt) while you’re at it?

**Comment by foobargeez** [comment]
> pushed to PAUSE as v0.4003 just now gentlemen

Thank you @majensen!

**Comment by majensen** [comment]
NP - also just pushed Neo4j::Bolt 0.4203

**Comment by johannessen** [comment]
Thanks!
