### ISSUE TITLE
query one db, then connect to and query a second

### ISSUE THREAD

**Issue by adambaker** [majensen/rest-neo4p#4]
I'm trying to restore some data on several remote servers from local backups (and wholesale replacement of neo's data directory is not an option). But REST::Neo4p seems to run into problems when I try doing something like this:

``` perl
use strict;
use warnings;
use 5.010;
use Data::Dumper;
use REST::Neo4p;

{
  REST::Neo4p->connect('http://127.0.0.1:7474');
  my $q = REST::Neo4p::Query->new('match (l:Language) return l');
  $q->{ResponseAsObjects} = 0;
  $q->execute;
  my %langs = map {$_->{_name} => $_} @{$q->fetch};
  $q->finish;
  say Dumper(\%langs);

  REST::Neo4p->connect($remote_url);
  $q = REST::Neo4p::Query->new('match (l:Language)<-(h:Hint) return l,h');
  $q->{ResponseAsObjects} = 0;
  $q->execute;
  say Dumper($q->fetch);
}
```

The Dump of %langs is what I expect. But then I get the error:
`Can't run fetch(), query not execute()'d yet`

I'm very confused as to why it says the query wasn't executed()'d yet. It seems like I'd just executed it. Any ideas?

**Comment by majensen** [comment]
Thanks for this-- I've wanted to see someone try this use case. The [DBD::Neo4p](https://github.com/majensen/dbd-neo4p) package is much better instrumented for multiple handles to multiple DBs. CAn you try with that like so:

```
use DBI;
{
  $dbh1  = DBI->connect("dbi:Neo4p:http://127.0.0.1:7474")
  $sth1 = $dbh1->prepare("match (l:Language) return l");
  $sth1->execute();
  ...
  $dbh2 = DBI->connect("dbi:Neo4p:$remote_url");
  $sth2 = $dbh2->prepare("...");
  $sth2->execute;
  say Dumper($sth->fetch);
  ...

}
```

With DBD::Neo4p  "ResponseAsObjects" is 0 by default, it does the finish() automatically,etc.
Let me know-

**Comment by adambaker** [comment]
I tried using DBD::Neo4p as well. I copied your DBI->connect statement and got:
`DBI connect('http://127.0.0.1:7474','',...) failed: Can't parse DSN part 'http://127.0.0.1:7474'`

**Comment by majensen** [comment]
Sorry about that ,put

dbi:Neo4p:db=127.0.0.1:7474

On Fri, Jun 12, 2015 at 3:29 PM, Adam C. Baker < notifications@github.com [notifications@github.com] > wrote:
I tried using DBD::Neo4p as well. I copied your DBI->connect statement and got:
DBI connect('http://127.0.0.1:7474','',...) failed: Can't parse DSN part
'http://127.0.0.1:7474'

—
Reply to this email directly or view it on GitHub
[https://github.com/majensen/rest-neo4p/issues/4#issuecomment-111595133] .[https://github.com/notifications/beacon/AAFAmZZRxvGi1t7f0ThLF2hmY9Jc2XyAks5oSyqigaJpZM4FAiTC.gif]

**Comment by adambaker** [comment]
Many thanks for your responses.
I ended up just talking HTTP to neo for the first query, and it ended up just being easier to proceed that way.
